export enum SlackChannel {
    OSMO_FUNDING = 'C05CNTC3YQZ',
    OSMO_WITHDRAW = 'C05C7A99E2H',
    FUNDING_TRANSFER = 'C06PHDU9X5J',
    FUNDING_FIAT = 'C06PMQZ4GLA',
    FUNDING_CARD = 'C06PMQWERKL',
    WITHDRAW_BANK = 'C06PMMPJJUB',
    TRANSACTIONS_STABLE_COINS = 'C06PJTDE73P',
    OSMO_STATUS_MONITOR = 'C05BE5QS6F7',
    STILLMAN_CHANNEL = 'C0708FGAXDF',
}
