export enum WithdrawalMethodEnum {
    STABLE_COIN = 'STABLE_COIN',
    TRANSFER = 'TRANSFER',
    CASH_WITHDRAWAL = 'CASH_WITHDRAWAL',
    CASH_OUT = 'CASH_OUT',
    TRANSFER_SOLFIN = 'TRANSFER_SOLFIN',
    AKISI = 'AKISI',
    SINPE = 'SINPE',
    SINPE_MOBILE = 'SINPE_MOBILE',
}
