
export enum FundingMethodEnum {
    TRANSFER = 'TRANSFER',
    CASH = 'CASH_FUNDING',
    STABLE_COIN = 'STABLE_COIN',
    CREDIT_CARD = 'CREDIT_CARD',
    TRANSFER_SOLFIN = 'TRANSFER_SOLFIN',
    AKISI = 'AKISI',
}