ALGOLIA_APP_ID=op://Osmowallet-PROD/Algolia/APP_ID
ALGOLIA_KEY=op://Osmowallet-PROD/Algolia/ADMIN_KEY

RELAMPAGO_WEBHOOK_SECRET=op://Osmowallet-PROD/Relampago/WEBHOOK_SECRET
RELAMPAGO_API_KEY_ID=op://Osmowallet-PROD/Relampago/ID
RELAMPAGO_API_KEY=op://Osmowallet-PROD/Relampago/API_KEY
RELAMPAGO_URL=op://Osmowallet-PROD/Relampago/url

THE_BITCOIN_COMPANY_API_KEY=op://Osmowallet-DEV/The Bitcoin Company/API_KEY
THE_BITCOIN_COMPANY_API_SECRET=op://Osmowallet-DEV/The Bitcoin Company/API_SECRET
THE_BITCOIN_COMPANY_WEBHOOK_SECRET=op://Osmowallet-DEV/The Bitcoin Company/WEBHOOK_SECRET
THE_BITCOIN_COMPANY_URL=op://Osmowallet-DEV/The Bitcoin Company/URL

SLACK_WEBHOOK_URL=op://Osmowallet-STG/Slack/WEBHOOK_URL

STRIKE_OSMO_WEBHOOK_SECRET=op://Osmowallet-PROD/Strike/OSMO_WEBHOOK_SECRET
STRIKE_API_KEY=op://Osmowallet-PROD/Strike/credential

ONVO_WEBHOOK_SECRET=op://Osmowallet-PROD/Onvo/WEBHOOK_SECRET
ONVO_PUBLIC_KEY=op://Osmowallet-PROD/Onvo/PUBLIC_KEY
ONVO_SECRET_KEY=op://Osmowallet-PROD/Onvo/SECRET_KEY

INFILE_NIT_EMISOR=op://Osmowallet-PROD/INFILE/NIT_EMISOR
INFILE_USUARIO_API=op://Osmowallet-PROD/INFILE/USUARIO_API
INFILE_LLAVE_API=op://Osmowallet-PROD/INFILE/LLAVE_API
INFILE_LLAVE_FIRMA=op://Osmowallet-PROD/INFILE/LLAVE_FIRMA

OSMO_MONEY_URL=op://Osmowallet-PROD/Server/MONEY_URL
OSMO_MONEY_API_KEY=op://Osmowallet-PROD/Server/MONEY_API_KEY

SENTRY_DSN=op://Osmowallet General/Sentry/dsnCore

EMAILABLE_KEY=op://OsmoWallet General/Emailable/password

ENV=op://OsmoWallet-PROD/Server/ENV
DOMAIN=op://OsmoWallet-PROD/Server/domain

APP_SUBDOMAIN=op://OsmoWallet-PROD/Server/APP_SUBDOMAIN

ADMIN_JWT_ACCESS_SECRET=op://OsmoWallet-PROD/Server/ADMIN_JWT_ACCESS_SECRET
ADMIN_JWT_REFRESH_SECRET=op://OsmoWallet-PROD/Server/ADMIN_JWT_REFRESH_SECRET
JWT_ACCESS_SECRET=op://OsmoWallet-PROD/Server/JWT_ACCESS_SECRET
JWT_REFRESH_SECRET=op://OsmoWallet-PROD/Server/JWT_REFRESH_SECRET
PARTNER_ACCESS_SECRET=op://OsmoWallet-PROD/Server/PARTNER_ACCESS_SECRET
PARTNER_REFRESH_SECRET=op://OsmoWallet-PROD/Server/PARTNER_ACCESS_SECRET
SESSION_LOGOUT_ALL_ACCESS_KEY=op://OsmoWallet-PROD/Server/SESSION_LOGOUT_ALL_ACCESS_KEY

ENCRYPTION_KEY=op://OsmoWallet-PROD/Server/ENCRYPTION_KEY
ENCRYPTION_IV=op://OsmoWallet-PROD/Server/ENCRYPTION_IV
PAYLOAD_ENCRYPTION_KEY=op://OsmoWallet-PROD/Server/PAYLOAD_ENCRYPTION_KEY
PAYLOAD_ENCRYPTION_IV=op://OsmoWallet-PROD/Server/PAYLOAD_ENCRYPTION_IV

DATABASE_MIGRATIONS_RUN=op://OsmoWallet-PROD/Database/MIGRATIONS_RUN
DATABASE_URL=op://OsmoWallet-PROD/Database/url

IBEX_OSMO_LNURL_ADDRESS_PAYER=op://OsmoWallet-PROD/Ibex/lnurlPayer
IBEX_NATIVE_OSMO_ACCOUNT_ID=op://OsmoWallet-PROD/Ibex/nativeAccountId
IBEX_NATIVE_OSMO_ACCOUNT_NAME=op://OsmoWallet-PROD/Ibex/nativeAccountName
IBEX_OSMO_ACCOUNT_ID=op://OsmoWallet-PROD/Ibex/accountId
IBEX_OSMO_ACCOUNT_NAME=op://OsmoWallet-PROD/Ibex/accountName
IBEX_BASE_URL=op://OsmoWallet-PROD/Ibex/url
IBEX_EMAIL=op://OsmoWallet-PROD/Ibex/username
IBEX_PASSWORD=op://OsmoWallet-PROD/Ibex/password
IBEX_WEBHOOK_SECRET=op://OsmoWallet-PROD/Ibex/WEBHOOK_SECRET

EXCHANGE_RATE_KEY=op://OsmoWallet General/ExchangeRate/credential
BCCR_TOKEN=op://OsmoWallet General/ExchangeRate/BCCR_TOKEN

SENDGRID_API_KEY=op://OsmoWallet General/Sendgrid/credential

GCLOUD_PROJECT_ID=op://OsmoWallet-PROD/Google Cloud/PROJECT_ID
GCLOUD_STORAGE_BUCKET_NAME=op://OsmoWallet-PROD/Google Cloud/BUCKET_NAME
GCLOUD_WEB_API_KEY=op://OsmoWallet-PROD/Google Cloud/WEB_API_KEY
GCLOUD_CLIENT_EMAIL=op://OsmoWallet-PROD/Google Cloud/CLIENT_EMAIL
GCLOUD_PRIVATE_KEY=op://OsmoWallet-PROD/Google Cloud/PRIVATE_KEY

GCLOUD_FUNCTIONS_API_KEY=op://OsmoWallet-STG/Google Cloud/apiKey

KYC_WEBHOOK_SECRET=op://OsmoWallet-PROD/Metamap/WEBHOOK_SECRET
KYC_BASE_URL=op://OsmoWallet-PROD/Metamap/API_BASE_URL
KYC_TOKEN=op://OsmoWallet-PROD/Metamap/TOKEN

TWILIO_ACCOUNT_SID=op://OsmoWallet General/Twilio/TWILIO_ACCOUNT_SID
TWILIO_AUTH_TOKEN=op://OsmoWallet General/Twilio/TWILIO_AUTH_TOKEN
TWILIO_PHONE=op://OsmoWallet General/Twilio/phone

MONGO_URL_CONNECTION=op://OsmoWallet-PROD/MongoDB/MONGO_URL_CONNECTION
MONGO_DB_NAME=op://OsmoWallet-PROD/MongoDB/MONGO_DB_NAME

REDIS_HOST=op://OsmoWallet-DEV/Redis/REDIS_HOST
REDIS_PORT=op://OsmoWallet-PROD/Redis/REDIS_PORT