

export enum AdminTransactionType {
    CREDIT_BTC_OSMO_BUSINESS = 'CREDIT_BTC_OSMO_BUSINESS',
    OSMO_CREDIT = 'OSMO_CREDIT',
    OSMO_DEBIT = 'OSMO_DEBIT',
    LIQUIDITY_BUY = 'LIQUIDITY_BUY',
    LIQUIDITY_SELL = 'LIQUIDITY_SELL',
}