export enum FeatureEnum {
    REFERRAL = 'REFERRAL',
    RECURRENT_BUY = 'RECURRENT_BUY',
    SEND = 'SEND',
    FUNDING = 'FUNDING',
    SWAP = 'SWAP',
    AUTOCONVERT = 'AUTOCONVERT',
    SCAN_TO_RECEIVE = 'SCAN_TO_RECEIVE',
    SEND_FIAT = 'SEND_FIAT',
    SEND_ON_CHAIN = 'SEND_ON_CHAIN',
    SEND_GLOBALLY = 'SEND_GLOBALLY',
    AUTOCONVERT_TO_SEND = 'AUTOCONVERT_TO_SEND',
    WITHDRAW = 'WITHDRAW',
}
