
export enum Status {
    PENDING = 'PENDING',
    COMPLETED = 'COMPLETED',
    CANCELED = 'CANCELED',
    CREATED = 'CREATED',
    REVIEW_NEEDED = 'REVIEW_NEEDED',
    REJECTED = 'REJECTED',
    IN_PROCESS = 'IN_PROCESS',
    FAILED = 'FAILED',
    VERIFIED = 'VERIFIED',
    PRE_APPROVED = 'PRE_APPROVED',
}