export enum TransactionType {
    SEND = 'SEND',
    AUTOCONVERT = 'AUTOCONVERT',
    SWAP = 'SWAP',
    RECEPTION = 'RECEPTION',
    WITHDRAW = 'WITHDRAW',
    CASHOUT = 'CASHOUT',
    FUNDING = 'FUNDING',
    REFERRAL = 'REFERRAL',
    TRANSACTION = 'TRANSACTION',
    RECURRENT_BUY = 'RECURRENT_BUY',
    //// ADMIN
    OSMO_CREDIT = 'OSMO_CREDIT',
    OSMO_DEBIT = 'OSMO_DEBIT',
    CREDIT_BTC_OSMO_BUSINESS = 'CREDIT_BTC_OSMO_BUSINESS',
    LIQUIDITY_SELL = 'LIQUIDITY_SELL',
    LIQUIDITY_BUY = 'LIQUIDITY_BUY',
}
